name: Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # ensure permissions for GHCR

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Run Docker Compose services
        run: docker compose up -d

      # Optionally run tests inside a container, e.g.:
      # - name: Run tests
      #   run: docker-compose exec <service_name> <test_command>

      - name: Tear down Docker Compose services
        run: docker compose down
